name: Zip Code Ingestion

on:
  push:
    paths:
      - 'zipcodesreduced.csv'
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Debug Java and Maven environment
      run: |
        echo "Java version:"
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        echo "PATH: $PATH"
        echo "Maven version:"
        mvn --version
        echo "Maven home:"
        mvn -v | grep "Maven home"
        echo "Java compiler version:"
        javac -version
        echo "Effective Maven settings:"
        mvn help:effective-settings
        echo "Listing .mvn directory:"
        ls -la .mvn || echo ".mvn directory not found"
        echo "Content of .mvn/jvm.config (if exists):"
        cat .mvn/jvm.config || echo ".mvn/jvm.config not found"
        echo "Content of pom.xml:"
        cat pom.xml

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -X

    - name: Run Zip Code Ingestion
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: java -jar target/zipcode-importer-0.0.1-SNAPSHOT.jar

    - name: Upload ingestion log
      uses: actions/upload-artifact@v4
      with:
        name: ingestion-log
        path: ingestion.log
